[project]
name = "backend"
version = "0.1.0"
description = "Pac-Map Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["fastapi>=0.116.1", "jupyterlab>=4.4.4", "uvicorn>=0.35.0"]
